/* Show Modals */
export const SET_CREATE_NEW_CLIENT_MODAL_STATUS = "SET_CREATE_NEW_CLIENT_MODAL_STATUS";
export const SET_EDIT_CLIENT_MODAL_STATUS = "SET_EDIT_CLIENT_MODAL_STATUS";
export const SET_SELECTED_USER_DETAILS = "SET_SELECTED_USER_DETAILS";
export const CLEAR_SELECTED_USER_DETAILS = "CLEAR_SELECTED_USER_DETAILS";